import = [
  "~\\AppData\\Roaming\\alacritty\\themes\\themes\\terminal_app.toml"
]

shell = "wsl.exe"
working_directory = "~/Documents/Github"

[window]
startup_mode = "Maximized"
resize_increments = true
decorations = "None"

[font]
normal = { family = "Cascadia Mono", style = "Regular" }
size = 10.0
