theme = "nightfox_custom.toml"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
left = ["version-control", "separator", "file-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "selections", "position"]

[editor.indent-guides]
render = true
character = "|"
skip-levels = 2

[keys.insert]
C-h = ["move_char_left"]
C-l = ["move_char_right"]
C-j = ["move_visual_line_down"]
C-k = ["move_visual_line_up"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = [ "extend_line_above" ]
A-x = [ "extend_to_line_bounds", "trim_selections" ]
