theme = "custom"

[editor]
scrolloff = 0
lsp.display-inlay-hints = true
lsp.display-messages = true

[editor.statusline]
left = ["mode", "version-control", "file-name", "file-modification-indicator"]
center = ["read-only-indicator", "total-line-numbers"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "workspace-diagnostics"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 2

[keys.insert]
j.j = ["normal_mode"]
C-h = ["move_char_left"]
C-l = ["move_char_right"]
C-j = ["move_visual_line_down"]
C-k = ["move_visual_line_up"]

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]
X = [ "extend_line_above" ]
A-x = [ "extend_to_line_bounds", "trim_selections" ]
