vim.cmd[[set completeopt=menuone,noselect,fuzzy complete=.,w,b,o tabstop=2 shiftwidth=2 softtabstop=2 cmdheight=0 signcolumn=no guicursor=a:block nowrap noshowmode noswapfile nobackup nowritebackup smartcase ignorecase smartindent autoindent expandtab showmatch autocomplete]]
vim.g.mapleader = ' '
vim.g.vimtex_view_method = 'zathura'
vim.keymap.set('n', 'gn', ':bn<CR>')
vim.keymap.set('n', 'gp', ':bp<CR>')
vim.keymap.set('n', 'go', ':lua vim.lsp.buf.workspace_symbol()<CR>')
vim.keymap.set('i', '<C-k>', '<Up>')
vim.keymap.set('i', '<C-j>', '<Down>')
vim.keymap.set('i', '<C-h>', '<Left>')
vim.keymap.set('i', '<C-l>', '<Right>')
vim.keymap.set('c', '<C-j>', '<Down>')
vim.keymap.set('c', '<C-k>', '<Up>')
vim.keymap.set('c', '<C-h>', '<Left>')
vim.keymap.set('c', '<C-l>', '<Right>')
vim.keymap.set('n', '<leader>l', ':cn<CR>', {silent = true, noremap = true})
vim.keymap.set('n', '<leader>h',  ':cp<CR>', {silent = true, noremap = true})
vim.keymap.set("n", "q", "<nop>", {})
vim.keymap.set({'n', 'v', 'i', 'c' }, 'ş', '<Esc>')
vim.keymap.set('t', 'ş', '<C-\\><C-N>')
vim.diagnostic.config({ virtual_text = true })
vim.cmd('au TextYankPost * silent! lua vim.hl.on_yank {higroup="IncSearch", timeout=500}')
vim.pack.add({"https://github.com/lervag/vimtex", "https://github.com/neovim/nvim-lspconfig"})
vim.lsp.inlay_hint.enable(true)
vim.lsp.enable({'pylsp', 'texlab', 'clangd'})
vim.cmd.colorscheme("catppuccin")
vim.api.nvim_set_hl(0, 'Normal', {bg='#000000'})
