code --install-extension asabil.meson
code --install-extension cschlosser.doxdocgen
code --install-extension EditorConfig.EditorConfig
code --install-extension GitHub.github-vscode-theme
code --install-extension Gruntfuggly.todo-tree
code --install-extension jbenden.c-cpp-flylint
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension mhutchie.git-graph
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.hexeditor
code --install-extension notskm.clang-tidy
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension xaver.clang-format
code --install-extension usernamehw.errorlens
code --install-extension rust-lang.rust-analyzer
code --install-extension bungcip.better-toml
code --install-extension adpyke.codesnap
